[package]
name = "scrypt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "scrypt"
path = "src/lib.rs"

[[bin]]
name = "scrypt"
path = "src/bin.rs"
